// ===== Пиксельные спрайты (8×8, у босса 16×16) =====

const PALETTE = {
  k: '#1a1418', w: '#f2efe6', g: '#9a9aa6', d: '#5a5a66', r: '#d8433c', o: '#e88a3a',
  y: '#ffd34e', b: '#8a5a34', B: '#5a3a24', n: '#d9b38c', p: '#f07fb4', G: '#5fbf5a',
  h: '#2f7a3c', u: '#3f7fe0', U: '#24508f', c: '#9fe2ff', v: '#9a5ad6', P: '#4a2f6e',
  s: '#f0c8a0', e: '#ff4040', m: '#c8ccd8', O: '#8a9a4a', Q: '#2a2238', a: '#ffb070',
};

const SPRITES = {
  player: [
    '..mmmm..',
    '.mmmmmm.',
    '.mskksm.',
    '..ssss..',
    '.uuyuuu.',
    's.uuuu.s',
    '..U..U..',
    '..B..B..',
  ],
  rat: [
    '........',
    '........',
    '.gg.....',
    'gkgggg..',
    'pgggggg.',
    '.g.g.g.p',
    '.......p',
    '........',
  ],
  bat: [
    '........',
    'P......P',
    'PP.PP.PP',
    'PPPePePP',
    '.PPPPPP.',
    '..P..P..',
    '........',
    '........',
  ],
  slime: [
    '........',
    '........',
    '...GG...',
    '..GGGG..',
    '.GwGGwG.',
    '.GkGGkG.',
    'GGGGGGGG',
    '.hhhhhh.',
  ],
  goblin: [
    'G.GGGG.G',
    '.GGGGGG.',
    '.GeGGeG.',
    '..GGGG..',
    '.bbbbbb.',
    'G.bbbb.G',
    '..b..b..',
    '..B..B..',
  ],
  kobold: [
    '......m.',
    '.oo...m.',
    'oeoo..m.',
    '.ooo..m.',
    'ooooo.b.',
    '.oooobb.',
    '.o..o.b.',
    '.B..B...',
  ],
  skeleton: [
    '..www...',
    '.wkwkw..',
    '.wwwww..',
    '..wkw...',
    '.wwwww..',
    'w.www.w.',
    '..w.w...',
    '.ww.ww..',
  ],
  archer: [
    '..www.b.',
    '.wkwkw.b',
    '.wwwww.b',
    '..wkw..b',
    '.wwwwwwb',
    'w.www..b',
    '..w.w.b.',
    '.ww.ww..',
  ],
  spider: [
    '........',
    'P..PP..P',
    '.P.PP.P.',
    '..PPPP..',
    'PPPePePP',
    '..PPPP..',
    '.P.PP.P.',
    'P......P',
  ],
  chest: [
    '........',
    '.bbbbbb.',
    'bBBBBBBb',
    'bbbyybbb',
    'bBByyBBb',
    'bbbbbbbb',
    'BBBBBBBB',
    '........',
  ],
  mimic: [
    '.bbbbbb.',
    'bBBBBBBb',
    'bwkwkwkb',
    'rrrrrrrr',
    'bkwkwkwb',
    'bbbbbbbb',
    'BBBBBBBB',
    '........',
  ],
  ghost: [
    '..wwww..',
    '.wwwwww.',
    'wwkwwkww',
    'wwwwwwww',
    'wwwkkwww',
    'wwwwwwww',
    'wwwwwwww',
    'w.ww.ww.',
  ],
  ogre: [
    '.OOOOOO.',
    'OOOOOOOO',
    'OOeOOeOO',
    'OOwOOwOO',
    '.OOOOOO.',
    'bOOOOOOb',
    'ObbbbbbO',
    '.OO..OO.',
  ],
  shade: [
    '..QQQQ..',
    '.QQQQQQ.',
    'QQeQQeQQ',
    'QQQQQQQQ',
    '.QQQQQQ.',
    'QQQQQQQQ',
    'Q.QQ.QQ.',
    '........',
  ],
  necro: [
    '..PPP..y',
    '.PPPPP.m',
    '.PekeP.m',
    '.PPPPP.m',
    'PPPPPPPm',
    '.PPvPP.m',
    '.PPPPP.m',
    '.P...P.m',
  ],
  puppy: [
    '........',
    '........',
    'nn......',
    'nknnnn..',
    'knnnnnnn',
    '.nnnnnn.',
    '.n.n.n.n',
    '........',
  ],
  merchant: [
    '..yyyy..',
    '.yyyyyy.',
    'yyyyyyyy',
    '..sksk..',
    '..wwww..',
    '.vwwwwv.',
    '.vvvvvv.',
    '.v....v.',
  ],
  cat: [
    '.o....o.',
    '.oo..oo.',
    '.oooooo.',
    '.oGooGo.',
    '.ooppoo.',
    'oooaaooo',
    'oooaaoo.',
    '.oo..oo.',
  ],
  potion: [
    '...bb...',
    '...gg...',
    '..gxxg..',
    '.gxxxxg.',
    '.gxwxxg.',
    '.gxxxxg.',
    '..gggg..',
    '........',
  ],
  scroll: [
    '........',
    '.nnnnnn.',
    'nwwwwwwn',
    '.wkkkkw.',
    '.wwwwww.',
    '.wkkkw..',
    'nwwwwwwn',
    '.nnnnnn.',
  ],
  wand: [
    '......c.',
    '.....cwc',
    '......c.',
    '.....b..',
    '....b...',
    '...b....',
    '..b.....',
    '.b......',
  ],
  pie: [
    '........',
    '........',
    '..oooo..',
    '.oyoyoo.',
    'oooooooo',
    'bbbbbbbb',
    '.bbbbbb.',
    '........',
  ],
  sausage: [
    '........',
    '........',
    'r.......',
    '.rrrrrr.',
    'rrppprrr',
    '.rrrrrr.',
    '.......r',
    '........',
  ],
  knife: [
    '........',
    '......m.',
    '.....mm.',
    '....mm..',
    '...mm...',
    '..bm....',
    '.bb.....',
    '........',
  ],
  gold: [
    '........',
    '........',
    '...yy...',
    '..yyyy..',
    '.yyoyyy.',
    'yyyyyoyy',
    '.oyyyyo.',
    '........',
  ],
  dagger: [
    '........',
    '......m.',
    '.....m..',
    '....m...',
    '...m....',
    '..yy....',
    '.b......',
    '........',
  ],
  sword: [
    '.......m',
    '......mm',
    '.....mm.',
    '....mm..',
    '.y.mm...',
    '..yy....',
    '.b.y....',
    'b.......',
  ],
  longsword: [
    '.......c',
    '......cm',
    '.....cm.',
    '....cm..',
    '.y.cm...',
    '..yy....',
    '.b.y....',
    'b.......',
  ],
  axe: [
    '....mm..',
    '...mmmm.',
    '...bmmm.',
    '..b.mm..',
    '.b......',
    'b.......',
    '........',
    '........',
  ],
  mace: [
    '....kk..',
    '...kddk.',
    '...kddk.',
    '....kk..',
    '...b....',
    '..b.....',
    '.b......',
    'b.......',
  ],
  hammer: [
    '..dddd..',
    '..dmmd..',
    '..dddd..',
    '...b....',
    '...b....',
    '...b....',
    '...b....',
    '...B....',
  ],
  leather: [
    '........',
    '.bb..bb.',
    '.bbbbbb.',
    '..bbbb..',
    '..bbbb..',
    '..bbbb..',
    '..BBBB..',
    '........',
  ],
  studded: [
    '........',
    '.bb..bb.',
    '.bybbyb.',
    '..bbbb..',
    '..ybby..',
    '..bbbb..',
    '..BBBB..',
    '........',
  ],
  chain: [
    '........',
    '.gg..gg.',
    '.gdgdgg.',
    '..gdgd..',
    '..dgdg..',
    '..gdgd..',
    '..dddd..',
    '........',
  ],
  scale: [
    '........',
    '.GG..GG.',
    '.GhGhGG.',
    '..hGhG..',
    '..GhGh..',
    '..hGhG..',
    '..hhhh..',
    '........',
  ],
  plate: [
    '........',
    '.mm..mm.',
    '.mwmmmm.',
    '..mwmm..',
    '..mmmm..',
    '..mmmm..',
    '..dddd..',
    '........',
  ],
  trap: [
    '........',
    '........',
    '...r....',
    '..r.r...',
    '.r...r..',
    '........',
    '.r.r.r..',
    '........',
  ],
  zzz: [
    '.wwww...',
    '...w....',
    '..w.....',
    '.wwww...',
    '........',
    '....www.',
    '.....w..',
    '....www.',
  ],
  dog: [
    '................',
    '..BB........BB..',
    '.BnnB......BnnB.',
    '.BnnnBBBBBBnnnB.',
    '..BnnnnnnnnnnB..',
    '..BnnnnnnnnnnB..',
    '.BnnkknnnnkknnB.',
    '.BnnkennnnkennB.',
    '.BnnnnnnnnnnnnB.',
    '.BnnnnwkkwnnnnB.',
    '..BnnnkkkknnnB..',
    '..BnnnnrrnnnnB..',
    '...BnnnrrnnnB...',
    '..BnnnnnnnnnnB..',
    '.BnnBnnnnnnBnnB.',
    '.BBB.BBBBBB.BBB.',
  ],
};

const _spriteCache = new Map();

// Готовый холст со спрайтом; tint заменяет пиксели 'x'
function getSprite(name, tint, overrideColor) {
  const key = name + '|' + (tint || '') + '|' + (overrideColor || '');
  let c = _spriteCache.get(key);
  if (c) return c;
  const rows = SPRITES[name] || SPRITES.potion;
  const h = rows.length, w = rows[0].length;
  c = document.createElement('canvas');
  c.width = w; c.height = h;
  const ctx = c.getContext('2d');
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const ch = rows[y][x];
      if (ch === '.') continue;
      let col = ch === 'x' ? (tint || '#c0c0c0') : PALETTE[ch];
      if (overrideColor) col = overrideColor;
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  _spriteCache.set(key, c);
  return c;
}
